### ISSUE TITLE
Boundaries

### ISSUE THREAD

**Issue by haydarkaraoglu** [CMU-Quake/hercules#11]
I have trouble figuring out where the BOUNDARY and HALFSPACE definitions are done. Does anyone know where they are defined?

**Comment by ricardotaborda** [comment]
You define the environment variables in your user.mk.  They take effect when compiling psolve.  In the code, they are in psolve.c.  Simply look for the environment variables `BOUNDARY` and `HALFSPACE` and you will see them.  `HALFSPACE` is used only once.  `BOUNDARY` is the one that you will see at more points in the code because it is used to setup the nodes conditions and also in the solution to make sure that the dashpots at the boundaries are considered.  The initial setup occurs in the methods `compute_setflag(...)` and `compute_setboundary(...)`.

Does this answers your question?
